spring.application.name=service-request-tracker
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/service_request_tracker}
spring.datasource.username=${DB_USERNAME:service_user}
spring.datasource.password=${DB_PASSWORD:local_dev_password}

spring.jpa.hibernate.ddl-auto=update